apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: eks-cluster
  region: us-east-2
  version: "1.21"

nodeGroups:
  - name: eks-node-group
    instanceType: t2.micro
    desiredCapacity: 1